description: "The repositories on my account contain personal projects, realized essentially for fun."
email: "eric.chopin@wanadoo.fr"
social-network-links:
  github: EricChopin
keywords: "python,science,microscopy,3D motion, fractals"
ORCID: 0000-0003-1258-9425
